In [3]:
import numpy as np

In [2]:
# Level 1: Creating Numpy Arrays

a=np.array([1,5,6,9,8])
print(a)

[1 5 6 9 8]


In [4]:
# Level 2: Arrays with Zeros And Ones

Zero=np.zeros(4)
one=np.ones((2,3))

print(Zero)
print()
print(one)

[0. 0. 0. 0.]

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Level 3: Random Number Arrays

random=np.random.rand(3,2)
print(random)

[[0.30191096 0.03522337]
 [0.48436934 0.88007812]
 [0.51823243 0.33645864]]


In [11]:
# Level 4: Reshaping Arrays

a=np.array([1,2,5,8,9,6])
print(a.reshape(3,2))

[[1 2]
 [5 8]
 [9 6]]


In [12]:
# Level 5: Array Indexing and Slicing

a=np.array([1,2,5,8,6])
print(a[2])
print(a[1:5])

5
[2 5 8 6]


In [14]:
# Level 6: basic mathematical Operations

a=np.array([1,5,8])
b=np.array([8,4,5])
r=a+b
print(r)

[ 9  9 13]


In [15]:
# Level 7: Statistical Operations

a=np.array([10,20,50,40,60])
print(np.mean(a))
print(np.median(a))
print(np.std(a))

36.0
40.0
18.547236990991408


In [16]:
# Level 8: Broadcasting

a=np.array([1,5,6])
r=a+5
print(r)

[ 6 10 11]


In [4]:
# Level 9:Boolean Indexing

a=np.array([12,15,18,16,23,24])
f=a[a>20]
print(f)

[23 24]


In [5]:
# Level 10: Vectorized Operations

a=np.array([1,2,3,4,5])
r=np.sqrt(a)
print(r)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [6]:
# Level 11: Liner Algebra Operations

a=np.array([[1,2],[3,4]])
b=np.array([[2,0],[1,2]])
product=np.dot(a,b)
determinant=np.linalg.det(a)
print(product)
print(determinant)


[[ 4  4]
 [10  8]]
-2.0000000000000004


In [7]:
# Level 12: Aggregation Functions

a=np.array([3,6,9,4])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.cumsum(a))

22
3
9
[ 3  9 18 22]


In [9]:
# Level 13: Sorting and Searching

a=np.array([15,22,25,86,6])
sort=np.sort(a)
index=np.where(a>25)
print(sort)
print(index)

[ 6 15 22 25 86]
(array([3]),)


In [10]:
# Level 14: Concatenation and Splitting

x=np.array([1,5,6,9])
y=np.array([8,6,3,2])
combined=np.concatenate((x,y))
split=np.split(combined,2)
print(combined)
print(split)

[1 5 6 9 8 6 3 2]
[array([1, 5, 6, 9]), array([8, 6, 3, 2])]


In [ ]:
# Level 15: DAta Type Conversion

a=np.array([2.5,6.5,7.9])